/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutMakautRouteImport } from './routes/about-makaut'
import { Route as AboutMcaRouteImport } from './routes/about-mca'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as CredRouteImport } from './routes/cred'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as HeadlinersRouteImport } from './routes/headliners'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as StoryRouteImport } from './routes/story'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMakautRoute = AboutMakautRouteImport.update({
  id: '/about-makaut',
  path: '/about-makaut',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMcaRoute = AboutMcaRouteImport.update({
  id: '/about-mca',
  path: '/about-mca',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const CredRoute = CredRouteImport.update({
  id: '/cred',
  path: '/cred',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadlinersRoute = HeadlinersRouteImport.update({
  id: '/headliners',
  path: '/headliners',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-makaut': typeof AboutMakautRoute
  '/about-mca': typeof AboutMcaRoute
  '/clubs': typeof ClubsRoute
  '/cred': typeof CredRoute
  '/experience': typeof ExperienceRoute
  '/headliners': typeof HeadlinersRoute
  '/journey': typeof JourneyRoute
  '/leadership': typeof LeadershipRoute
  '/schedule': typeof ScheduleRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-makaut': typeof AboutMakautRoute
  '/about-mca': typeof AboutMcaRoute
  '/clubs': typeof ClubsRoute
  '/cred': typeof CredRoute
  '/experience': typeof ExperienceRoute
  '/headliners': typeof HeadlinersRoute
  '/journey': typeof JourneyRoute
  '/leadership': typeof LeadershipRoute
  '/schedule': typeof ScheduleRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-makaut': typeof AboutMakautRoute
  '/about-mca': typeof AboutMcaRoute
  '/clubs': typeof ClubsRoute
  '/cred': typeof CredRoute
  '/experience': typeof ExperienceRoute
  '/headliners': typeof HeadlinersRoute
  '/journey': typeof JourneyRoute
  '/leadership': typeof LeadershipRoute
  '/schedule': typeof ScheduleRoute
  '/story': typeof StoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-makaut'
    | '/about-mca'
    | '/clubs'
    | '/cred'
    | '/experience'
    | '/headliners'
    | '/journey'
    | '/leadership'
    | '/schedule'
    | '/story'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-makaut'
    | '/about-mca'
    | '/clubs'
    | '/cred'
    | '/experience'
    | '/headliners'
    | '/journey'
    | '/leadership'
    | '/schedule'
    | '/story'
  id:
    | '__root__'
    | '/'
    | '/about-makaut'
    | '/about-mca'
    | '/clubs'
    | '/cred'
    | '/experience'
    | '/headliners'
    | '/journey'
    | '/leadership'
    | '/schedule'
    | '/story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMakautRoute: typeof AboutMakautRoute
  AboutMcaRoute: typeof AboutMcaRoute
  ClubsRoute: typeof ClubsRoute
  CredRoute: typeof CredRoute
  ExperienceRoute: typeof ExperienceRoute
  HeadlinersRoute: typeof HeadlinersRoute
  JourneyRoute: typeof JourneyRoute
  LeadershipRoute: typeof LeadershipRoute
  ScheduleRoute: typeof ScheduleRoute
  StoryRoute: typeof StoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-makaut': {
      id: '/about-makaut'
      path: '/about-makaut'
      fullPath: '/about-makaut'
      preLoaderRoute: typeof AboutMakautRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-mca': {
      id: '/about-mca'
      path: '/about-mca'
      fullPath: '/about-mca'
      preLoaderRoute: typeof AboutMcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cred': {
      id: '/cred'
      path: '/cred'
      fullPath: '/cred'
      preLoaderRoute: typeof CredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headliners': {
      id: '/headliners'
      path: '/headliners'
      fullPath: '/headliners'
      preLoaderRoute: typeof HeadlinersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMakautRoute: AboutMakautRoute,
  AboutMcaRoute: AboutMcaRoute,
  ClubsRoute: ClubsRoute,
  CredRoute: CredRoute,
  ExperienceRoute: ExperienceRoute,
  HeadlinersRoute: HeadlinersRoute,
  JourneyRoute: JourneyRoute,
  LeadershipRoute: LeadershipRoute,
  ScheduleRoute: ScheduleRoute,
  StoryRoute: StoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
